---
- name: Install wget and unzip
  apt:
    name: wget

- name: Download vault zip at /tmp/ folder
  shell: mkdir tmp && cd tmp && wget https://releases.hashicorp.com/vault/1.12.0/vault_1.12.0_linux_amd64.zip

- name: Unzip vault zip
  shell: unzip vault_1.12.0_linux_amd64.zip && rm vault_1.12.0_linux_amd64.zip

- name: Move vault binary
  shell: mv /tmp/vault /usr/local/bin/vault